version: '3'
services:
  client:
    build:
       context: ./phoenix-tool-client
       dockerfile: Dockerfile
    ports:
      - "80:80"
  server:
    build:
       context: ./phoenix-tool-server
       dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 1s
      timeout: 30s
  tests:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    depends_on:
      - client
      - server
    command: >
        sh -c "npm run test"
